### ISSUE TITLE
[REQUEST][Oxygen-Groups] More options to move player health UI

### ISSUE THREAD

**Issue by SeriousCreeper** [AustereTony-MCMods/Oxygen-Core#11]
I'm using some UI mods such as IgniteHUD to change the HUD layout/design. A lot of info is on the left side of the screen, which overlaps with the Oxygen Groups player huds (i can provide a screenshot of this later).

Unfortunately the groups hud can't be shifted enough to fix overlap from the looks of it. 
Something like a right-side anchor would help a ton, so it can all align on the right screen no matter the size of the window.

Cheers,
SC

**Comment by AustereTony-MCMods** [comment]
Hello
Thanks for the suggestion. This feature has been added and will be available with version 0.11 soon

**Comment by SeriousCreeper** [comment]
Thanks a lot!

**Comment by AustereTony-MCMods** [comment]
Added in 0.11
