### ISSUE TITLE
[ISSUE][DailyRewards - 0.11.0] DailyReward Not Available anymore

### ISSUE THREAD

**Issue by SeriousCreeper** [AustereTony-MCMods/Oxygen-Core#15]
**Describe the bug**
I was using DailyRewards in my pack and all seemed to work fine, up until i updated to 0.11.0. While i still see the rewards, i can no longer claim them: https://i.imgur.com/RAsA2KU.png 

Looking at the config it seems to be enabled still, though something i noticed is that there is a typo in one of the option:
`"daily_reards_access": true,` 
(this is how it was generated by default).

Not sure if that could have any effect?

**Comment by AustereTony-MCMods** [comment]
Hello
Try to change "maximum_rewards_amount_per_month" config value to 31

**Comment by SeriousCreeper** [comment]
Aha, that worked! Thanks a lot!
