### ISSUE TITLE
 Configure economy with EnderPay impossible

### ISSUE THREAD

**Issue by E-Auvergne** [AustereTony-MCMods/Oxygen-Core#17]
**Hello,**

I don't understand how to configure the economy, I installed EnderPay and Oxygen and all the modules, but the currency is still the Oxygen Coin, I looked at the wiki and the configuration files but, I can't find anything, how to configure the currency to allow EnderPay to be the main currency of Oxygen?

**thank you in advance**

**Bonjour,**

Je ne comprends pas comment configurer l'économie, j'ai installé EnderPay et Oxygen et tous les modules, mais la monnaie est toujours l'Oxygen Coin, j'ai regardé le wiki et les fichiers de configuration mais, je ne trouve rien, comment configurer la devise pour permettre à EnderPay d'être la devise principale d'Oxygen?

**Merci d'avance**

**Comment by AustereTony-MCMods** [comment]
Hello
There is no way to link Oxygen to EnderPay directly, so you will need Grand Economy and Grand Economy Currency Provider. 
1) Configure Grand Economy to "bridge" mode for EnderPay (set "economyBridge=enderpay" in GE config). 
2) Set "force_balance_sync" to "true" in Grand Economy Currency Provider config.

All configs will be created after first game start after mods installation.

**Comment by E-Auvergne** [comment]
Thank you !
