### ISSUE TITLE
[Gui Glitch] [Mail - 0.11.0] Gui glitches sometimes when opening

### ISSUE THREAD

**Issue by Kakiharu** [AustereTony-MCMods/Oxygen-Core#19]
**Describe the bug**
The Gui does not display mail when opening sometime, closing and reopening multiple times temporally fixes it.

**To Reproduce**
Use the hotkey or command to open the mail a few times.

Optional:

https://imgur.com/a/KFkAfw3

**Comment by AustereTony-MCMods** [comment]
Hello
This is spam protection from the client by requests for data synchronization. When you open most of the menus, the data is updated and synchronized if necessary. The cooldown of synchronization is 2 seconds.
So you can open menu only once per 2 seconds.
