### ISSUE TITLE
[resolved] Cant acces to gui for privilege management due to FTB LIB/FTB utilities

### ISSUE THREAD

**Issue by DaFray31** [AustereTony-MCMods/Oxygen-Core#21]
I cant acces to gui for setting up oxygen, oxygen say : " you dont have permission"
I m OP of the server. (/oxygenc core -privileges -management) the commande oxygenc doesnt exist.

**Comment by DaFray31** [comment]
Found, ftb lib "delet" the oxygenc command

**Comment by DaFray31** [comment]
for using ftb utilities with oxygen , just in the cfg file (of ftb utilities)
change at ranks change all to false :
```
ranks {
    # Enables ranks and adds command.x permissions and allows ranks to control them.
    B:enabled=false

    # Adds chat colors/rank-specific syntax.
    B:override_chat=false

    # Allow to configure commands with ranks. Disable this if you want to use other permission mod for that.
    B:override_commands=false
}
```

**Comment by AustereTony-MCMods** [comment]
Thank you for information, i will add it to Wiki.
