### ISSUE TITLE
Support for GrandEconomy

### ISSUE THREAD

**Issue by xyberviri** [AustereTony-MCMods/Oxygen-Core#4]
Hello, i love this project, is there any chance you can add support for grand economy?

https://github.com/The-Fireplace-Minecraft-Mods/Grand-Economy

There is some code in this for how its accessed from ResearchTable
https://github.com/ZengineeringTeam/ResearchTable/blob/faefd08235ec1e63ea1d4146d81f7401a5d90545/src/main/java/snownee/researchtable/plugin/grandeconomy/GrandEconomyPlugin.java

Another mod called FreeTrading also has support for this mod, but it has its own api so it can support multiple currency systems:
https://github.com/Foghrye4/Freetrading/blob/master/src/main/java/freetrading/mod_interaction/ge_integration/GrandEconomyIntegrationUtil.java

all of interaction between that mod and the currency mods takes place in that class and between these lines in this one other class:
https://github.com/Foghrye4/Freetrading/blob/98758bd62132f6813f3b3930b6aa0a4e0c15a566/src/main/java/freetrading/trading_system/TradingSystem.java#L310-L339

**Comment by AustereTony-MCMods** [comment]
Sure, if it will be useful. Oxygen trading system still WIP, so i will look into other projects support later. Thank you for suggestion and for using my project.

**Comment by AustereTony-MCMods** [comment]
It took a while. Connecting currencies from other mods is available using special mod providers. Providers are available on the official Curse [page](https://www.curseforge.com/minecraft/mc-mods/oxygen-currency-providers). Support is currently only available for Grand Economy.
