### ISSUE TITLE
Many Oxygen Mods and Grandeconomy works not with the new 0.9.0 versions Updates

### ISSUE THREAD

**Issue by Titoo8899** [AustereTony-MCMods/Oxygen-Core#6]
HI,

please Update your mods: Oxygen Exchange, Friends List, Groups, Interaction, Merchants (Oxygen version) and Teleportaion. All this have a 0.8.0, 1 or 2 and work not with the new Updates of the other Oxygen 0.9.0 version. And one other think the grandeconomy works not he say Version 1.2.0 have we not. Please fix it and Update it.

**Comment by AustereTony-MCMods** [comment]
Hello.
All modules will be updated within a couple of weeks.

**Comment by AustereTony-MCMods** [comment]
All modules updated. Closed.
